apiVersion: v1
kind: Pod
metadata:
  name: with-node-affinity
  labels:
    app: pause
    applicationId: "pod-with-node-affinity-01"
    queue: "root.sandbox"
spec:
  schedulerName: yunikorn
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: kubernetes.io/e2e-az-name
                operator: In
                values:
                  - e2e-az1
                  - e2e-az2
  containers:
    - name: with-node-affinity
      image: k8s.gcr.io/pause:2.0
      resources:
        requests:
          cpu: "100m"
          memory: "500M"