apiVersion: v1
kind: Pod
metadata:
  labels:
    app: sleep
    applicationId: "sleep0001-node-selector-test"
    queue: "root.sandbox"
  name: task1
spec:
  schedulerName: yunikorn
  containers:
    - name: sleep-5s
      image: "alpine:latest"
      command: ["sleep", "300"]
      resources:
        requests:
          cpu: "100m"
          memory: "500M"
  nodeSelector:
    nodetype: test